### ISSUE TITLE
Feature: Support for AvroName and AvroEncode attribute

### ISSUE THREAD

**Issue by RobertIndie** [eaba/AvroSchemaGenerator#10]
It would be better if we can add support for [AvroName](http://avro.apache.org/docs/1.7.6/api/java/org/apache/avro/reflect/AvroName.html) and [AvroEncode](http://avro.apache.org/docs/1.7.6/api/java/org/apache/avro/reflect/AvroEncode.html) like in java.

Using the AvroName attribute we can add better support for schema forward compatibility.
Using the AvroEncode attribute we can resolve the issue with the absence of DateTime support in Avro: https://github.com/eaba/AvroSchemaGenerator/issues/9

**Comment by eaba** [comment]
http://avro.apache.org/docs/current/spec.html#Time+%28millisecond+precision%29

**Comment by eaba** [comment]
@RobertIndie released fix https://www.nuget.org/packages/AvroSchemaGenerator/1.9.0-beta.2

**Comment by eaba** [comment]
Logical Types are supported when using `SpecificDatumReader` , `SpecificDatumWriter` and not supported in `ReflectReader`,  `ReflectWriter`

**Comment by RobertIndie** [comment]
@eaba Thank you! But how can we use the `AvroName` feature? Or is it currently unimplemented?

**Comment by eaba** [comment]
> http://avro.apache.org/docs/current/spec.html#Time+%28millisecond+precision%29

This library helps to generate Avro Schema declaration and not to port Avro java. 

Take a at the link  above and let me know where the AvroName falls so I can understand you better.
