### ISSUE TITLE
Wrong version in Nuget Pacakge 

### ISSUE THREAD

**Issue by AndriiPpoliukhovychIntelcomexpress** [eaba/AvroSchemaGenerator#25]
I do see version 1.9.0 inside the 2.3.0 nuget package 
![image](https://user-images.githubusercontent.com/84515829/133470156-11a3abb2-587e-44e1-80fb-a440cbfe9079.png)

**Comment by eaba** [comment]
@AndriiPpoliukhovychIntelcomexpress Thanks for the catch.

The issue has been fixed with [2.3.3](https://www.nuget.org/packages/AvroSchemaGenerator/2.3.3).

Kindly confirm!
