### ISSUE TITLE
Breaking change in schema generation

### ISSUE THREAD

**Issue by Lanayx** [eaba/AvroSchemaGenerator#33]
Hi! I've just updated from 1.9 to 2.3.3 version and got the [integration test](https://github.com/fsharplang-ru/pulsar-client-dotnet/blob/fsharpsix/tests/IntegrationTests/Schema.fs#L309-L365) failing

What happens is that the following class

```fsharp
[<CLIMutable>]
type SimpleRecord =
    {
        Name: string
        Age: int
    }
```
used to generate this schema in 1.9

`{"type":"record","namespace":"Pulsar.Client.IntegrationTests","name":"SimpleRecord","fields":[{"name":"Name","type":["null","string"],"default":null},{"name":"Age","type":"int"}]}`

in 2.3.3 it generates this schema

`{"namespace":"Pulsar.Client.IntegrationTests","name":"SimpleRecord","type":"record","fields":[{"name":"Name","type":["null","string"]},{"name":"Age","type":"int"}]}`

As you can see `"default":null` parameter is missing and I'm getting `org.apache.pulsar.broker.service.schema.exceptions.IncompatibleSchemaException` when adding Surname field

```fsharp
[<CLIMutable; Aliases("SimpleRecord")>]
type SimpleRecord2 =
    {
        Name: string
        Age: int
        Surname: string
    }
```
Can you please return the former behavior, since DefaultValue(null) doesn't work either, it fails with `null not a "string" caused by org.apache.avro.AvroTypeException`

**Comment by eaba** [comment]
Hi @Lanayx 
Can you try `[DefaultValue("null")]`?

**Comment by Lanayx** [comment]
Hi! This will probably default to string "null" which is not a desired behavior

**Comment by eaba** [comment]
@Lanayx I want you to help so that I can understand the problem very well!
Did the `aliases` work prior to upgrading to 2.0?

**Comment by Lanayx** [comment]
@eaba Yes, the aliases worked

**Comment by Lanayx** [comment]
If I specify `[<DefaultValue("abc")>]`, it works as well

**Comment by eaba** [comment]
Thanks.
It appears anything except `null` works. 
I passed in an empty string and it worked!
What do we do?

**Comment by Lanayx** [comment]
As `null` has a cornerstone type in avro, I don't think dropping it's support is a good idea, so I suggest to return back to 1.9 behaviour where `default: null` is generated in schema for nullable reference types and nullable value types.
![image](https://user-images.githubusercontent.com/3329606/135091504-8ad52da7-74b3-4345-9fde-857cc167bdc9.png)

**Comment by Lanayx** [comment]
Another way is to make `DefaultValue(null)` work, I'm ok with it as well.

**Comment by Lanayx** [comment]
BTW, here is the issue with `DefaultValue(null)`, the generated schema is
`{"namespace":"Pulsar.Client.IntegrationTests","name":"SimpleRecord2","aliases":["SimpleRecord"],"type":"record","fields":[{"name":"Name","type":["null","string"]},{"name":"Age","type":"int"},{"name":"Surname","type":"string","default":null}]}`, as you can see null doesn't present in Surname type

**Comment by Lanayx** [comment]
A problem with new approach is that all fields are kinda marked as [Required], which is opposite to previous behavior
![image](https://user-images.githubusercontent.com/3329606/135095695-e58b48f5-877c-46bc-a0c2-aed26d1b2a43.png)

**Comment by eaba** [comment]
@Lanayx please can test this out https://www.nuget.org/packages/AvroSchemaGenerator/2.4.0-beta?

**Comment by Lanayx** [comment]
@eaba Thank you, it worked

**Comment by Lanayx** [comment]
@eaba will you release non-beta package?

**Comment by eaba** [comment]
> 
> 
> @eaba will you release non-beta package?

Yes, in like 20 minutes max!
