### ISSUE TITLE
Support for Avro name aliases

### ISSUE THREAD

**Issue by richardwilko** [eaba/AvroSchemaGenerator#4]
Please consider adding support for [aliases](https://avro.apache.org/docs/current/spec.html#Aliases) in the generated schema.

This could be added in the same way as default value with a custom annotation, e.g.

```c#
[Aliases("OldCourse")]
public class Course
    {
        [DefaultValue("200")]
        [Aliases("Level")]
        public string NewLevel { get; set; }
    }
```

**Comment by eaba** [comment]
Ok but no ETA yet.
Thanks

**Comment by eaba** [comment]
Guess this issue has been fixed!
