### ISSUE TITLE
.NET standard 2.0 support

### ISSUE THREAD

**Issue by Lanayx** [eaba/AvroSchemaGenerator#40]
Hi! Can you please return back .NET Standard 2.0 support? Pulsar.Client supports 2.0, so we can't get updated to 2.5.0

**Comment by eaba** [comment]
2.5.0 has no changes just .NET 6 target added

**Comment by Lanayx** [comment]
![image](https://user-images.githubusercontent.com/3329606/149380802-68f28bfd-2dfd-4d0a-8a2b-af34e7d7638f.png)
This was a breaking change

**Comment by eaba** [comment]
What I meant was that I only changed the framework the code still remains as before 2.5.0

**Comment by eaba** [comment]
I know there are businesses using your software, maybe it is time to encourage them to move from .netstandards and not remain there forever. You don't need to update to 2.5.0 because the features still the same with 2.4. Only i moved from supporting 2.0 and 2.1

**Comment by marcwittke** [comment]
> maybe it is time to encourage them to move from .netstandards and not remain there forever.

I think you misunderstand the reasoning behind .NET Standards. It is there to stay forever, and as a library developer you should always target the lowest possible netstandard available, considering the tradeoff related to it. See https://docs.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-1-0#when-to-target-net50-or-net60-vs-netstandard for more details.

You are targeting net5.0 and net6.0 what actually is the framework equivalent of depending on a concrete implementation instead of depending on an interface.

**Comment by eaba** [comment]
> It is there to stay forever

Sure. 

Staying forever and being maintained/supported forever are different.

.NET Standards will continue to exist, but I don't think it will be maintained forever. As a matter of facts, .NET Standard 2.1 is the last .NET Standard. Microsoft is abandoning that ship gradually.

In the same light, `AvroSchemaGenerator` 2.4.*  is here to stay forever. If you need .NET standards support, you could always use the version with the framework support you need!

**Comment by marcwittke** [comment]
Do you have any source that confirms your statement? I mean, [that page](https://docs.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-1-0#net-standard-not-deprecated) literally says the opposite and I am really interested to hear, how they plan to support alternative runtimes like xamarin et al without having the .NET Standard definition.

**Comment by eaba** [comment]
> .NET Standard 2.1 is the last .NET Standard

Meaning don't expect .NET Standards 2.2/3.0 - if you are creating a new project then use newer frameworks. 

We can't tell Microsoft to back port features from .NET 6 into .NET Standards, because a project depends on .NET Standards!

**Comment by marcwittke** [comment]
Sure, that's what I do with my applications, that sit on the end of the dependency food chain. But we're talking about a library that is supposed to be consumed by others. By

> I only changed the framework the code still remains as before 2.5.0

you are basically excluding possible consumers out of a nothing. As long as you don't rely on net5.0 exclusive APIs and therefore do not have any reason not to do so you should really continue to support netstandard. 

And by the way (although you nowhere state explicitly sticking to it): following semver would have forced you to bump the major version when removing a set of supported runtimes.

**Comment by eaba** [comment]
Fixed in 2.6.0
