### ISSUE TITLE
Add ability to ignore some properties

### ISSUE THREAD

**Issue by elnur-m** [eaba/AvroSchemaGenerator#5]
Hi! Can you, please, add ability to ignore some properties? E.g. [Ignore] attribute or some kind of another implementation.

**Comment by eaba** [comment]
Hi @elnur-m sorry for the delayed response.
Why would you want to ignore some properties? Why not instead remove it?

**Comment by elnur-m** [comment]
I'm using this [pulsar client](https://github.com/fsharplang-ru/pulsar-client-dotnet) in my project, which is using AvroSchemaGenerator for schemas. I'm also using protobuf-net for serialization. I get exceptions like "`DateTime format is not supported`" when I add a property of `DateTime` type to my schema, so I decided to save the timestamp as a `long` and to add a computed `DateTime` property for convenience.

```C#
public long TimestampAsLong {get;set} = DateTime.Now.ToBinary();
//I need to ignore this one
public DateTime TimestampAsDateTime => DateTime.FromBinary(Timestamp);
```
So I need to ignore the second property as it's not a part of the schema, but just for convenience

**Comment by eaba** [comment]
Avro does not have a `DateTime` type.
When the Consumer receives the message, you can create another object that has `TimestampAsDateTime` property.

**Comment by elnur-m** [comment]
No problem, I'll overcome this issue in some another way.
Just proposed this feature because the class is in a shared library and used both by consumer and the producer.
You can close the issue, thanks!

**Comment by eaba** [comment]
You are welcome!

**Comment by JarrodJ83** [comment]
I could use this functionality as well and believe there is a legitimate use case for it. I am trying to do the same as @elnur-m. I want to be able to leverage DateTime and other types that are not supported in Avro but only for purpose of making my code easier to understand and work with, not for adding these props to the schema. As a workaround I am currently generating my pocos from avro files (so there is a schema property pulsar.client leverages) then adding these properties using partial classes. While this works it is a clunky developer experience. 

If I get some time I'll try to create a PR for such an enhancement. Until then I just wanted to provide some additional justification for @elnur-m 's request.

**Comment by eaba** [comment]
@elnur-m @JarrodJ83 just pushed a new commit with Ignore attribute added....please test to see if this solves your problem before I release it to nuget.

**Comment by eaba** [comment]
@elnur-m @JarrodJ83 still awaiting your feedback. 
Thanks!

**Comment by elnur-m** [comment]
Sorry for the late feedback. I gave it a quick try – it worked!
After you release it, I'll ask the maintainer of the pulsar client to update it and after it I'll know definetely if it solves my problem.
But I'm pretty sure that it will. Thank you so much!

**Comment by eaba** [comment]
Done 1.7.0
