### ISSUE TITLE
Exceptions when trying to use this on protoc generated files

### ISSUE THREAD

**Issue by richardwilko** [eaba/AvroSchemaGenerator#6]
Hi, I'm using this library as part of the pulsar-client-dotnet.  This project has some logic which will try and generate an avro schema from the protoc generated c sharp classes, but this fails as the generated class has some static  fields relating to protobuf, which aren't compatible with this library.

However, it seems the intention of this library isn't really to recuse into static fields anyway, and if I modify the code so that wherever you are calling `GetProperties()`, to only fetch public instance fields by doing `GetProperties(BindingFlags.Instance | BindingFlags.Public)`, all the tests still pass, but it solves the issues around these static generated fields.

What do you think of this?

**Comment by eaba** [comment]
Can you create a PR with your modifications?

**Comment by richardwilko** [comment]
Created PR https://github.com/eaba/AvroSchemaGenerator/pull/7

**Comment by eaba** [comment]
Thank you.

Released on nuget
