### ISSUE TITLE
Any plans to support nested schemas?

### ISSUE THREAD

**Issue by JarrodJ83** [eaba/AvroSchemaGenerator#8]
I was wondering if there were any plans to support nested schemas? I have a need to use a type multiple times in my schema and currently that results in a "Duplicate schema name" exception when Avro tries to parse the schema generated by AvroSchemaGenerator. I have created a failing unit test to show by example: https://github.com/JarrodJ83/AvroSchemaGenerator/commit/fab86ce974b053427a4dd10e872322e686494c15

**Comment by eaba** [comment]
@JarrodJ83 just seeing this - I will take a look.

**Comment by eaba** [comment]
Investigated - please allow some time to get your request fulfilled. 
Thanks!

**Comment by eaba** [comment]
Hello @JarrodJ83 
Please take a look at this [branch](https://github.com/eaba/AvroSchemaGenerator/tree/nested_schema)
Right now there is an infinite recursion bug in avro for which I have submitted a [PR](https://github.com/apache/avro/pull/1187)
