### ISSUE TITLE
DateTime not supported in schema

### ISSUE THREAD

**Issue by RobertIndie** [eaba/AvroSchemaGenerator#9]
When I use a DateTime type field in the schema, it throws an Exception:
```
System.ArgumentException: DateTime not supported
   at AvroSchemaGenerator.GenerateSchema.ToAvroDataType(String type)
   at AvroSchemaGenerator.GenerateSchema.GetField(PropertyInfo p)
   at AvroSchemaGenerator.GenerateSchema.AddFields(PropertyInfo p, Dictionary`2 finalSchema)
   at AvroSchemaGenerator.GenerateSchema.PropertyInfo(PropertyInfo property, Dictionary`2 finalSchema)
   at AvroSchemaGenerator.GenerateSchema.GetSchema(Type type)
```

Sample c# code:
```csharp
class MessageDate
{
    public DateTime CreatedTime { get; set; }
}

[Fact]
public async Task DateSchema()
{
    typeof(MessageDate).GetSchema();
}
```

Is it that DateTime cannot be used here? It would be better if we can support DateTime in the schema.

**Comment by Lanayx** [comment]
Since AVRO has many representation of DateTime, I can suggest adding an attribute that takes enum parameter. The enum will contain all possible avro options)

**Comment by eaba** [comment]
Hi, 
Just seeing this....i will look into it.
Thanks

**Comment by eaba** [comment]
I will leave this here till when I have the time to work on this. Logical types
http://avro.apache.org/docs/current/spec.html#Time+%28millisecond+precision%29

**Comment by eaba** [comment]
@RobertIndie @Lanayx  released fix https://www.nuget.org/packages/AvroSchemaGenerator/1.9.0-beta.2

**Comment by eaba** [comment]
Logical Types are supported when using `SpecificDatumReader` , `SpecificDatumWriter` and not supported in `ReflectReader`,  `ReflectWriter`
